print("Train Info:")
train.info()
print("\nTest Info:")
test.info()
print("\nTrain Describe:")
display(train.describe(include='all'))
print("\nMissing values in train dataset:")
print(train.isnull().sum())
print("\nSurvived value counts:")
print(train['Survived'].value_counts())
print("\nPclass value counts:")
print(train['Pclass'].value_counts())
print("\nSex value counts:")
print(train['Sex'].value_counts())
